### model
model_name_or_path: LLaMA-Factory/saves/dynamicrag_llama3_8b

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: llama3_generator_dpo, llama3_reranker_dpo
template: llama3
cutoff_len: 8192
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
#
output_dir: saves/dynamicrag_llama3_8b_dpo/
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: llama3_reranker_dpo
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000000000