### model
model_name_or_path: dynamicRAG/models/generator/llama3_8b

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: alpaca_data, reranker_bc, generator_sft
template: llama3
cutoff_len: 8192
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/dynamicrag_llama3_8b/
logging_steps: 1
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: alpaca_en_demo
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000000000
